#include "WB3_stylemaster.h"

QString WB3_Stylemaster::setRegularStyle()
{
    return
    "#BottomLeftCorner{"
    "   background: url(:/Text-Block-5/Textures PNG/Angle-2-B-L.png)"
    "}"
    ""
    "#BottomRightCorner{"
    "   background: url(:/Text-Block-5/Textures PNG/Angle-2-B-R.png)"
    "}"
    ""
    "#TopLeftCorner{"
    "   background: url(:/Text-Block-5/Textures PNG/Angle-2-T-L.png)"
    "}"
    ""
    "#TopRightCorner{"
    "   background: url(:/Text-Block-5/Textures PNG/Angle-2-T-R.png)"
    "}"
    ""
    "#OpenworkBorderBottom{"
    "   background:url(:/Text-Block-5/Textures PNG/Border-2-B.png);"
    "}"
    ""
    "#OpenworkBorderLeft{"
    "   background:url(:/Text-Block-5/Textures PNG/Border-2-L.png);"
    "}"
    ""
    "#OpenworkBorderRight{"
    "   background:url(:/Text-Block-5/Textures PNG/Border-2-R.png);"
    "}"
    ""
    "#OpenworkBorderTop{"
    "   background:url(:/Text-Block-5/Textures PNG/Border-2-T.png);"
    "}"
    ""
    "#SolidBorder1{"
    "   border: 1px solid #83763f;"
    "}"
    ""
    "#SolidBorder2{"
    "   border: 1px solid #bec340;"
    "}";
}
